language: node_js
node_js:
  - '4'

before_install:
  - 'NPM_VERSION="$(npm --version)"; [ ${NPM_VERSION:0:1} == "3" ] || npm install -g npm'
  - npm --version

install:
  - npm install

script:
  - npm test

before_cache:
  - npm prune

cache:
  # https://docs.travis-ci.com/user/caching/
  directories:
    # Global node_modules
    - '$(npm config --global get prefix)/bin/'
    - '$(npm config --global get prefix)/lib/node_modules/'
    # Project node_modules
    - $(pwd)/node_modules/

services:
  - redis-server
